codecov:
  branch: master

coverage:
  status:
    project:
      default:
        target: 84%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 5%
        base: auto

component_management:
  individual_components:
    - component_id: core
      name: Core Library
      paths:
        - crates/unet-core/**
      
    - component_id: server
      name: Server API
      paths:
        - crates/unet-server/**
        
    - component_id: cli
      name: CLI Interface
      paths:
        - crates/unet-cli/**
        
    - component_id: migrations
      name: Database Migrations
      paths:
        - crates/migrations/**
        
    - component_id: config-slicer
      name: Config Utilities
      paths:
        - crates/config-slicer/**

  ignore:
    # Test files (already ignored by llvm-cov regex, but explicit here)
    - "**/*test*.rs"
    - "**/tests/"
    - "tests/"
    # Examples and benchmarks
    - "**/examples/"
    - "**/benches/"
    # Generated migration files
    - "crates/migrations/src/m*.rs"

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false

github_checks:
  annotations: true