codecov:
  branch: master

coverage:
  status:
    project:
      default:
        target: 84%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 5%
        base: auto

  ignore:
    # Test files (already ignored by llvm-cov regex, but explicit here)
    - "**/*test*.rs"
    - "**/tests/"
    - "tests/"
    # Examples and benchmarks
    - "**/examples/"
    - "**/benches/"
    # Generated migration files
    - "crates/migrations/src/m*.rs"

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false

github_checks:
  annotations: true