allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-panic-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true

# SNMP and network automation specific allowances
allowed-idents-below-min-chars = ["id", "ip", "io", "tx", "rx"]
