gitignore: true

globs:
  - "**/*.md"

ignores:
  - ".claude/**"
  - ".taskmaster/**"
  - "AGENTS.md"
  - "CLAUDE.md"
  - "TODO.md"
  - "FIXME.md"
  - "target/**"
  - "docs/archive/**"
  - "docs/static/**"

config:
  # MD013/line-length - Line length
  MD013:
    code_blocks: false
    tables: false
