# Pre-commit configuration for Î¼Net
# Run `pre-commit install` to set up the git hooks

repos:
  # Rust-specific hooks
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Format Rust code
        entry: cargo fmt
        language: system
        types: [rust]
        pass_filenames: false
        
      - id: cargo-clippy
        name: Lint Rust code
        entry: cargo clippy
        args: [--workspace, --all-targets, --all-features, --, -D, warnings]
        language: system
        types: [rust]
        pass_filenames: false
        
      - id: cargo-test
        name: Run Rust tests
        entry: cargo test
        args: [--workspace]
        language: system
        types: [rust]
        pass_filenames: false

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
        exclude: \.md$
      - id: mixed-line-ending
      - id: check-executables-have-shebangs

  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: [--fix, --disable, MD013, MD033, MD041]

  # Security
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.25.0
    hooks:
      - id: ggshield
        language: python
        stages: [commit]