# Clippy configuration for Î¼Net
# Minimal working configuration

# Basic thresholds
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 10
type-complexity-threshold = 250
too-many-lines-threshold = 150

# Testing allowances
allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-panic-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true

# SNMP and network automation specific allowances  
allowed-idents-below-min-chars = ["i", "j", "x", "y", "id", "ip", "io", "tx", "rx"]