min_version = '2024.11.1'

[tools]
rust = { version = "latest", components = "rustc,cargo,clippy,rustfmt,rust-std,rust-analyzer,rust-src,llvm-tools-preview" }
cargo-binstall = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-tarpaulin" = "latest"
typos = "latest"
"npm:markdownlint-cli2" = "latest"

[tasks.lint]
description = "Fix code issues and run linters"
run = [
  "typos -w",
  "cargo clippy --workspace --allow-dirty --fix --frozen",
  "cargo fmt",
]

[tasks.test]
description = "Run unit tests"
run = [
  "cargo llvm-cov --workspace --all-features --all-targets --show-missing-lines --frozen --no-clean nextest",
]

[tasks.check-large-files]
description = "Find files exceeding size guidelines (>400 lines)"
run = [
  "find crates -name '*.rs' -exec wc -l {} + | awk '$1 > 400 {print $0}' | sort -nr",
]
