min_version = '2024.11.1'
[settings]
idiomatic_version_file_enable_tools = ["rust"]

[tools]
rust = { version = "latest", components = "rustc,cargo,clippy,rustfmt,rust-std,rust-analyzer,rust-src,llvm-tools-preview" }
cargo-binstall = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-nextest" = "latest"
typos = "latest"
"npm:markdownlint-cli2" = "latest"

[tasks.lint]
description = "Fix code issues and run linters"
run = ["typos -w", "cargo fmt", "cargo clippy --workspace --allow-dirty --fix"]

[tasks.test]
description = "Run unit tests"
run = ["cargo nextest run"]

[tasks.coverage]
description = "Generate code coverage report and enforce minimum threshold"
run = [
  "cargo llvm-cov nextest --workspace --all-features --all-targets --show-missing-lines --ignore-filename-regex '(tests?\\.rs|_tests?\\.rs|comprehensive_tests\\.rs)$' --fail-under-lines 84",
]

[tasks.coverage-report]
description = "Generate code coverage report without enforcement (for development)"
run = ["cargo llvm-cov nextest --all-features --show-missing-lines --ignore-filename-regex '(tests?\\.rs|_tests?\\.rs|comprehensive_tests\\.rs)$' report"]

[tasks.check-large-files]
description = "Find files exceeding size guidelines (>400 lines)"
run = [
  "find crates -name '*.rs' -exec wc -l {} + | awk '$1 > 400 {print $0}' | sort -nr",
]

[tasks.clean]
description = "Clean build artifacts"
run = "cargo clean"

# Pre-commit hook - reuses existing CI tasks
[tasks.pre-commit]
description = "Pre-commit checks (same as CI lint task)"
depends = ["lint"]
