min_version = '2024.11.1'
[settings]
idiomatic_version_file_enable_tools = ["rust"]

[tools]
rust = { version = "latest", components = "rustc,cargo,clippy,rustfmt,rust-std,rust-analyzer,rust-src,llvm-tools-preview" }
cargo-binstall = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-tarpaulin" = "latest"
typos = "latest"
"npm:markdownlint-cli2" = "latest"

[tasks.lint]
description = "Fix code issues and run linters"
run = [
  "rustup component add --toolchain stable rustfmt",
  "typos -w",
  "cargo fmt",
  "cargo clippy --workspace --allow-dirty --fix",
]

[tasks.test]
description = "Run unit tests"
run = ["cargo nextest run"]

[tasks.coverage]
description = "Generate code coverage report and enforce minimum threshold"
run = [
  "cargo llvm-cov --workspace --all-features --all-targets --show-missing-lines --fail-under-lines 80",
]

[tasks.coverage-report]
description = "Generate code coverage report without enforcement (for development)"
run = ["cargo llvm-cov --all-features --show-missing-lines report"]

[tasks.check-large-files]
description = "Find files exceeding size guidelines (>400 lines)"
run = [
  "find crates -name '*.rs' -exec wc -l {} + | awk '$1 > 400 {print $0}' | sort -nr",
]
