min_version = '2024.11.1'
[settings]
idiomatic_version_file_enable_tools = ["rust"]

[tools]
rust = { version = "latest", components = "rustc,cargo,clippy,rustfmt,rust-std,rust-analyzer,rust-src,llvm-tools-preview" }
cargo-binstall = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-nextest" = "latest"
typos = "latest"
"npm:markdownlint-cli2" = "latest"

[tasks.lint]
description = "Fix code issues and run linters"
run = ["typos -w", "cargo fmt", "cargo clippy --workspace --allow-dirty --fix"]

[tasks.test]
description = "Run unit tests"
run = ["cargo nextest run"]

## Removed quiet test task in favor of single 'status' task.

[tasks.coverage]
description = "Generate code coverage report and enforce minimum threshold"
env = { COVERAGE_THRESHOLD = "84", COVERAGE_IGNORE_PATTERN = '(tests?\.rs|_tests?\.rs|comprehensive_tests\.rs)$' }
run = [
  "cargo llvm-cov nextest --workspace --all-features --all-targets --show-missing-lines --ignore-filename-regex \"$COVERAGE_IGNORE_PATTERN\"",
]

## Removed quiet coverage task in favor of single 'status' task.

[tasks.ci-coverage]
description = "Generate coverage report with LCOV output for CI"
env = { COVERAGE_THRESHOLD = "84", COVERAGE_IGNORE_PATTERN = '(tests?\.rs|_tests?\.rs|comprehensive_tests\.rs)$' }
run = [
  "cargo llvm-cov nextest --workspace --all-features --all-targets --show-missing-lines --ignore-filename-regex \"$COVERAGE_IGNORE_PATTERN\" --lcov --output-path lcov.info",
]

[tasks.ci-lint]
description = "Run linting and formatting checks for CI"
depends = ["lint"]

[tasks.ci-test]
description = "Run unit tests for CI"
run = ["cargo nextest run --profile ci"]

[tasks.ci-coverage-enforce]
description = "Enforce coverage threshold for CI"
env = { COVERAGE_THRESHOLD = "84" }
run = ["cargo llvm-cov report --fail-under-lines $COVERAGE_THRESHOLD"]

[tasks.ci-check-large-files]
description = "Find files exceeding size guidelines (>400 lines)"
depends = ["check-large-files"]

[tasks.check-large-files]
description = "Find files exceeding size guidelines (>400 lines)"
run = [
  "find crates -name '*.rs' -exec wc -l {} + | awk '$1 > 400 {print $0}' | sort -nr",
]

[tasks.ci-audit]
description = "Security audit for dependencies"
run = ["cargo audit"]

[tasks.ci-docs]
description = "Build API documentation"
run = ["cargo doc --workspace --no-deps --document-private-items"]

[tasks.pre-commit]
description = "Pre-commit checks"
depends = ["lint"]

[tasks.status]
description = "LLM-friendly project status overview (clippy + coverage tests + summaries)"
run = [
  "bash scripts/status-llm.sh",
]

## Removed 'overview' alias to reduce task duplication. Use 'status'.
