min_version = '2024.11.1'

[tasks.lint]
description = "Fix code issues and run linters"
run = [
  "typos -w",
  "cargo clippy --workspace --allow-dirty --fix --frozen",
  "cargo fmt",
]

[tasks.test]
description = "Run unit tests"
run = [
  "cargo llvm-cov --workspace --all-features --all-targets --show-missing-lines --frozen --no-clean nextest",
]

[tasks.check-large-files]
description = "Find files exceeding size guidelines (>400 lines)"
run = [
  "find crates -name '*.rs' -exec wc -l {} + | awk '$1 > 400 {print $0}' | sort -nr",
]
