name: Bug Report
description: File a bug report to help us improve μNet
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! This helps us improve μNet for everyone.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Configure nodes with '...'
        3. Apply policy '...'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which μNet component is affected?
      options:
        - μNet CLI
        - μNet Server
        - Policy Engine
        - Template Engine
        - Config Slicer
        - Database/Migrations
        - Git Integration
        - API Endpoints
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: μNet Version
      description: What version of μNet are you running?
      placeholder: "Example: 0.1.0, main branch"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide details about your environment:
      value: |
        - OS: [e.g. Ubuntu 22.04, macOS 14.0, Windows 11]
        - Rust version: [output of `rustc --version`]
        - Database: [SQLite/PostgreSQL version]
        - Deployment: [Docker, bare metal, Kubernetes, etc.]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: configuration
    attributes:
      label: Configuration files
      description: If relevant, please provide configuration files (remove sensitive data)
      render: toml

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission checklist
      description: Please verify these before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all requested information above
          required: true
        - label: I have removed any sensitive information from logs and configs
          required: true