blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/your-org/unet/tree/main/docs
    about: Check our comprehensive documentation for guides and examples
  - name: ðŸ’¬ Discussions
    url: https://github.com/your-org/unet/discussions
    about: Ask questions and discuss Î¼Net with the community
  - name: ðŸ”’ Security Issues
    url: mailto:security@your-org.com
    about: Report security vulnerabilities privately via email