name: Feature Request
description: Suggest an idea or enhancement for μNet
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Feature requests help us understand what μNet users need.

  - type: textarea
    id: problem-description
    attributes:
      label: Problem or Use Case
      description: Is your feature request related to a problem? Please describe the use case.
      placeholder: |
        Example: "I'm always frustrated when I need to manage network configurations across multiple vendors..."
        or "As a network engineer, I need to..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which area of μNet would this feature affect?
      options:
        - CLI Interface
        - API Endpoints
        - Policy Engine
        - Template System
        - Configuration Management
        - Git Integration
        - Database/Storage
        - Security/Authentication
        - Performance/Scalability
        - Monitoring/Observability
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to your workflow?
      options:
        - Critical - Blocking current work
        - High - Would significantly improve workflow
        - Medium - Nice to have improvement
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context, mockups, examples, or screenshots about the feature request here.
        If you have specific implementation ideas, feel free to share them.

  - type: textarea
    id: example-usage
    attributes:
      label: Example Usage
      description: If applicable, provide an example of how this feature would be used
      placeholder: |
        Example CLI command, API call, or configuration:
        ```bash
        unet nodes create --template cisco-switch --location "datacenter-1"
        ```
      render: bash

  - type: checkboxes
    id: implementation-willingness
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help with testing and feedback
        - label: I can provide domain expertise/consultation
        - label: I would prefer someone else implements this

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission checklist
      description: Please verify these before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear use case and proposed solution
          required: true
        - label: This feature aligns with μNet's core mission of network configuration management
          required: true