# Î¼Net Development Environment Configuration
# Based on development.toml template optimized for local development
#
# This configuration provides:
# - SQLite database for simplicity
# - Relaxed security for development ease
# - Verbose logging and debugging
# - Disabled features that complicate local development

[database]
url = "sqlite:./unet-dev.db?mode=rwc"
max_connections = 10
timeout = 30

[database.pool]
min_connections = 1
max_connections = 10
acquire_timeout = 30
max_lifetime = 1800
idle_timeout = 300
test_query = "SELECT 1"

[database.migration]
auto_migrate = true
timeout = 300
lock_timeout = 60

[logging]
level = "debug"
format = "pretty"
file = "./logs/unet-dev.log"

[logging.opentelemetry]
enabled = false
service_name = "unet-development"
service_version = "dev"
environment = "development"
sample_rate = 1.0

[logging.aggregation]
enabled = false
rotation = { max_size_mb = 10, max_files = 5, schedule = "daily" }
parsing = { enabled = true, indexed_fields = ["timestamp", "level", "message"], enrichment = false }

[logging.alerting]
enabled = false
rules = []
channels = []

[snmp]
community = "public"
timeout = 5
retries = 3

[server]
host = "127.0.0.1"
port = 8080
max_request_size = 1048576

# TLS disabled for development
# [server.tls]
# cert_file = "./dev-certs/dev.crt"
# key_file = "./dev-certs/dev.key"
# force_https = false

[git]
policies_repo = "./dev-policies"
templates_repo = "./dev-templates"
branch = "main"
sync_interval = 60

[domain]
default_domain = "dev.local"
search_domains = ["local", "dev"]

[auth]
enabled = false
jwt_secret = "dev-secret-key-not-for-production"
token_expiry = 86400

[secrets]
enabled = false
provider = "file"

[secrets.file_provider]
secrets_dir = "./dev-secrets"
encryption_enabled = false

[network]
enabled = false
allowed_ips = ["127.0.0.1", "::1"]
allowed_ranges = ["192.168.0.0/16", "10.0.0.0/8", "172.16.0.0/12"]
enable_geolocation = false
enable_network_rate_limits = false

[metrics]
enabled = true
endpoint = "/metrics"
collection_interval = 30
enable_performance_metrics = true
enable_business_metrics = true
enable_system_metrics = false
retention_days = 1

[metrics.labels]
service = "unet"
version = "dev"
environment = "development"

[load_balancer]
enabled = false
shutdown_timeout = 10

[load_balancer.health_check]
basic_path = "/health"
timeout = 3
include_dependencies = true
check_interval = 60

[cluster]
enabled = false

[shared_state]
backend = "memory"
default_expiry_seconds = 300

[stateless]
enabled = false

[resource_management]
enabled = false

[resource_management.memory]
max_cache_size_mb = 256
cache_ttl_seconds = 300
enable_memory_pooling = false
monitoring_enabled = false

[resource_management.limits]
max_cpu_percent = 95.0
max_memory_mb = 2048
max_concurrent_requests = 100
request_timeout_seconds = 60

[resource_management.throttling]
cpu_throttle_threshold = 95.0
memory_throttle_threshold = 95.0
user_request_quotas = { default = 1000 }
rate_limit_window_seconds = 60

[resource_management.degradation]
enable_circuit_breakers = false
fallback_response_enabled = false
reduce_functionality_on_overload = false

[resource_management.monitoring]
enable_detailed_metrics = false
metrics_collection_interval = 60
alert_thresholds = { cpu = 90.0, memory = 90.0 }
capacity_planning_enabled = false