{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "unet.fullname" . }}
  labels:
    {{- include "unet.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "unet.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
  endpoints:
  - port: metrics
    path: /metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
    honorLabels: false
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}