[book]
authors = ["μNet Development Team"]
language = "en"
multilingual = false
src = "src"
title = "μNet Documentation"
description = "Comprehensive documentation for μNet network configuration management system"

[rust]
edition = "2021"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/example/unet"
git-repository-icon = "fa-github"
print.enable = true
search.enable = true
site-url = "/unet/"