apiVersion: v1
kind: ConfigMap
metadata:
  name: unet-config
  namespace: unet
  labels:
    app.kubernetes.io/name: unet
    app.kubernetes.io/component: config
data:
  # Default configuration
  config.toml: |
    [server]
    host = "0.0.0.0"
    port = 8080
    tls_port = 8443
    
    [database]
    url = "sqlite:///app/data/unet.db"
    max_connections = 10
    
    [logging]
    level = "info"
    format = "json"
    
    [snmp]
    timeout = "30s"
    retries = 3
    
    [git]
    sync_interval = "300s"
    
    [security]
    jwt_secret_key = "change-this-in-production"
    session_timeout = "24h"
    
    [metrics]
    enabled = true
    endpoint = "/metrics"
  
  # Load balancer configuration
  config-load-balancer.toml: |
    [load_balancer]
    enabled = true
    health_check_interval = "30s"
    health_check_timeout = "10s"
    health_check_path = "/health"
    
    [load_balancer.aws_alb]
    enabled = true
    target_group_health_check = true
    
    [load_balancer.kubernetes]
    enabled = true
    service_type = "LoadBalancer"
    readiness_probe = true
    liveness_probe = true
  
  # PostgreSQL configuration
  config-postgres.toml: |
    [database]
    url = "postgres://unet:password@postgres:5432/unet"
    max_connections = 20
    min_connections = 5
    max_lifetime = "30m"
    acquire_timeout = "30s"
    idle_timeout = "10m"
    
    [database.performance]
    enable_connection_pooling = true
    enable_prepared_statements = true
    enable_query_caching = true