apiVersion: v1
kind: Namespace
metadata:
  name: unet
  labels:
    app.kubernetes.io/name: unet
    app.kubernetes.io/part-of: unet
  annotations:
    kubernetes.io/description: "Î¼Net network configuration management system"