apiVersion: v1
kind: Secret
metadata:
  name: unet-secrets
  namespace: unet-dev
type: Opaque
stringData:
  jwt-secret-key: "dev-jwt-secret-key-change-in-production"
  database-url: "sqlite:///app/data/unet.db"
  postgres-password: "dev_password"
  redis-url: "redis://dev-redis:6379"
  snmp-community-ro: "public"
  snmp-community-rw: "private"
  git-username: "dev-user"
  git-token: "dev-token"