name: Preflight

on:
  pull_request:
    branches: [master]

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - run: mise install
      - name: Ensure clippy is installed
        run: |
          rustup component add clippy rustfmt
      - run: cargo fetch
      - run: mise run lint
      - run: mise run test
      - run: mise run check-large-files
